name: Test with Testcontainers

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Docker (for Testcontainers)
        run: sudo apt-get update && sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test